#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_lucky_number:
  path: /lucky/number
  controller: App\Controller\LuckyController::number

blog_list:
  path: /blog
  controller: App\Controller\BlogController::list

api_post_show:
  path: /api/posts/{id}
  controller: App\Controller\BlogApiController::show
  methods: GET|HEAD

api_post_edit:
  path: /api/posts/{id}
  controller: App\Controller\BlogApiController::edit
  methods: PUT

blog_show:
  path: /blog/{slug}
  controller: App\Controller\BlogController::show
